In [1]:
"""https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba"""

In [2]:
import pandas as pd
import numpy as np
from scipy import stats


In [3]:
df=pd.read_csv('features.csv')
# x_df=df.drop(columns=['action'])
# y_df=df['action']

In [4]:
z = np.abs(stats.zscore(df))
print(z)

[[1.72952042 1.04180893 1.2252944  ... 1.65338178 0.73703765 1.37871091]
 [1.72445594 1.04180893 1.2252944  ... 1.2184139  0.85042806 1.37871091]
 [1.71939145 0.9598689  1.2252944  ... 0.93123433 0.73703765 1.37871091]
 ...
 [1.71939145 0.9598689  1.92151925 ... 0.93123433 1.30398969 1.46819705]
 [1.72445594 1.04180893 1.92151925 ... 0.93123433 1.64416091 1.37871091]
 [1.72952042 1.04180893 1.92151925 ... 0.93123433 1.75755132 0.66698392]]


In [5]:
threshold = 3
print(np.where(z > 3))

(array([  0,   0,   0, ..., 508, 509, 509], dtype=int64), array([212, 226, 240, ..., 273, 272, 273], dtype=int64))


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Columns: 286 entries, Unnamed: 0 to weekday (t-20)
dtypes: float64(260), int64(26)
memory usage: 1.5 MB


In [7]:
df = df[(z < 3).all(axis=1)]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 589 entries, 6 to 683
Columns: 286 entries, Unnamed: 0 to weekday (t-20)
dtypes: float64(260), int64(26)
memory usage: 1.3 MB


In [9]:
df.to_csv('clean_features.csv')