In [1]:
"""https://towardsdatascience.com/ways-to-detect-and-remove-the-outliers-404d16608dba"""

In [2]:
import pandas as pd
import numpy as np
from scipy import stats


In [3]:
df_num=pd.read_csv('numeric_features.csv')
df_cat=pd.read_csv('categorical_features.csv')
# x_df=df.drop(columns=['action'])
# y_df=df['action']

In [4]:
z = np.abs(stats.zscore(df_num))
print(z)

[[1.73045958 0.27468603 0.34336737 ... 1.10519065 0.45628814 0.05055933]
 [1.72727566 0.26242719 0.02992901 ... 1.15812179 0.49596659 0.09242766]
 [1.72409174 0.12757988 0.37819385 ... 1.23751851 0.48375783 0.10531023]
 ...
 [1.72409174 1.06152817 0.31833583 ... 0.99088272 0.65165625 0.76426287]
 [1.72727566 1.08604586 0.06475549 ... 0.8744342  0.55398622 0.67086428]
 [1.73045958 1.1228224  0.09958198 ... 1.3455214  0.83173536 0.98326646]]


In [5]:
threshold = 3
print(np.where(z > 3))

(array([133, 134, 134, ..., 827, 828, 829], dtype=int64), array([  7,   6,   7, ..., 155, 164, 173], dtype=int64))


In [6]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1088 entries, 0 to 1087
Columns: 181 entries, Unnamed: 0 to WTI | P2 | HSK (t-20)
dtypes: float64(180), int64(1)
memory usage: 1.5 MB


In [7]:
df_num = df_num[(z < 3).all(axis=1)]

In [8]:
df_cat = df_cat[(z < 3).all(axis=1)]

In [9]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 924 entries, 0 to 1087
Columns: 181 entries, Unnamed: 0 to WTI | P2 | HSK (t-20)
dtypes: float64(180), int64(1)
memory usage: 1.3 MB


In [10]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 924 entries, 0 to 1087
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              924 non-null    int64
 1   year                    924 non-null    int64
 2   month                   924 non-null    int64
 3   month_day               924 non-null    int64
 4   weekday                 924 non-null    int64
 5   target_position         924 non-null    int64
 6   target_position (t-1)   924 non-null    int64
 7   target_position (t-2)   924 non-null    int64
 8   target_position (t-3)   924 non-null    int64
 9   target_position (t-4)   924 non-null    int64
 10  target_position (t-5)   924 non-null    int64
 11  target_position (t-6)   924 non-null    int64
 12  target_position (t-7)   924 non-null    int64
 13  target_position (t-8)   924 non-null    int64
 14  target_position (t-9)   924 non-null    int64
 15  target_position (t-10)

In [11]:
df_num.to_csv('clean_numeric_features.csv')
df_cat.to_csv('clean_categorical_features.csv')